name: Build and Publish on github

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop

      - name: Build Application
        run: flutter build linux --release

      - name: Create Zip Release Linux
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: linux_release.zip
          path: build/linux/x64/release/bundle


  #      - name: Create Release On Github
  #        id: create-new-release-linux
  #        uses: actions/create-release@v1
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        with:
  #          tag_name: tag_${{ github.run_number }}_linux
  #          release_name: Release_${{ github.run_number }}_Linux
  #
  #
  #      - name: Upload Release Artifact
  #        uses: actions/upload-release-asset@v1
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        with:
  #          upload_url: ${{ steps.create-new-release-linux.outputs.upload_url }}
  #          asset_name: linux_release-v${{ github.run_number }}.zip
  #          asset_path: ./linux_release.zip
  #          asset_content_type: application/zip

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_linux
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Draft Release
        run: |
          ls
          gh release create ${{ github.ref }} --draft --generate-notes --title 'R_${{ github.run_number }}_Linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
