name: Build Artifacts

on:
  push:
    branches:
      - master

jobs:
  build_desktop_artifacts:
    name: Build and publish desktop artifacts
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, windows-latest ]
        include:
          - os: ubuntu-latest
            os_ver: 22
            os_name: linux
            build_output: build/linux/x64/debug/bundle
          - os: ubuntu-20.04
            os_ver: 20
            os_name: linux
            build_output: build/linux/x64/debug/bundle
          - os: windows-latest
            os_ver: 2022
            os_name: windows
            build_output: build\windows\runner\Debug
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:${{ hashFiles('**/pubspec.lock') }}" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - if: ${{ matrix.os_name == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build Application
        run: |
          flutter config --enable-${{ matrix.os_name }}-desktop
          flutter build ${{ matrix.os_name }} --debug

      - name: Add Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.os_name }}-${{ matrix.os_ver }}_build
          path: ${{ matrix.build_output }}
