name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Windows Artifact
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Add Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: git_build_genration_test_windows
          path: build\windows\runner\Release


  build_linux:
    name: Linux Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - name: Add Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: git_build_genration_test_linux
          path: build/linux/x64/release/bundle
