name: Publish To Other Repo

on:
  push:
    branches:
      - other_rep_push

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Draft Release
        run: gh release create tag_${{ github.run_number }} --generate-notes --title 'Release_${{ github.run_number }}' -R https://github.com/dilwarSingh/git_build_release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_RELEASE_TEST_TOKEN }}
