name: Build Artifacts

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Windows Artifact
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:${{ hashFiles('**/pubspec.lock') }}" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Add Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows_build
          path: build\windows\runner\Release


  build_linux:
    name: Linux Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:${{ hashFiles('**/pubspec.lock') }}" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --release
      - name: Add Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: linux_build
          path: build/linux/x64/release/bundle